name: smart_guide
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: any
  english_words: ^4.0.0
  provider: ^6.0.0
  firebase_auth: ^5.3.4
  firebase_core: ^3.10.1
  firebase_database: ^11.3.1
  cloud_firestore: ^5.6.2
  firebase_storage: ^12.4.5
  geocoding: ^2.1.0
  location: ^5.0.0
  carousel_slider: ^5.0.0
  http: ^1.3.0
  google_sign_in: ^6.3.0
  file_picker: 8.3.7
  dotted_border: ^2.1.0
  dynamic_multi_step_form: ^1.1.2+6
  google_fonts: ^6.2.1
  camera: ^0.11.1

  # url_launcher: ^6.0.20
  # english_words: ^4.0.0
  # provider: ^6.0.0
  # google_fonts: ^6.1.0 # To use Google Fonts for text styling
  # flutter_svg: ^2.0.7 # To include vector icons like the bell
  # font_awesome_flutter: ^10.5.0 # For icons (alternative)
  # cupertino_icons: ^1.0.2 # Default Cupertino icons
  # cached_network_image: ^3.3.0 # For efficient image handling
  # flutter_rating_bar: ^4.0.1 # Optional, for custom UI components

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/azrieli_college.png
    - assets/hebrew_university.png
    - assets/profile.png
    - assets/app.png
    - assets/AR.png
